apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas:
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: jettcanavarro/allgroundup:worker
        ports:
          - name: http-port
            containerPort: 80
