apiVersion: v1
kind: Service
metadata:
  name: webui-service
  labels:
    app: webui
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 31000 ##might need to change
  selector:
    app: webui

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
