CREATE TABLE ZIP (
    ZIP_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CITY_NAME VARCHAR(50) NULL,
    STATE VARCHAR(10) NULL,
    ZIP VARCHAR(5) NULL
);

CREATE TABLE COFFEE_SHOP (
    SHOP_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ZIP_ID INT NULL,
    SHOP_NAME VARCHAR(50) NULL,
    SHOP_ADDRESS VARCHAR(100) NULL,
    FOREIGN KEY (ZIP_ID) REFERENCES ZIP (ZIP_ID)
);

CREATE TABLE CUSTOMER (
    CUSTOMER_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    FIRST_NAME VARCHAR(50) NULL,
    LAST_NAME VARCHAR(50) NULL,
    USERNAME VARCHAR(100) NULL,
    PASSWORD VARCHAR(100) NULL,
    EMAIL VARCHAR(100) NULL,
    PHONE VARCHAR(50) NULL,
    CUSTOMER_ADDRESS VARCHAR(100) NULL,
    ZIP_ID INT NULL,
    FOREIGN KEY (ZIP_ID) REFERENCES ZIP (ZIP_ID)
);

CREATE TABLE STATUS_CATALOG (
    STATUS_CATALOG_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    STATUS_NAME VARCHAR(100) NULL
);

CREATE TABLE PLACED_ORDER (
    PLACED_ORDER_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER_ID INT NULL,
    ORDER_TIME TIMESTAMP NULL,
    PRICE DECIMAL(10, 2) NULL,
    COMMENT VARCHAR(100) NULL,
    SHOP_ID INT NULL,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (CUSTOMER_ID),
    FOREIGN KEY (SHOP_ID) REFERENCES COFFEE_SHOP(SHOP_ID)
);

CREATE TABLE ORDER_STATUS (
    STATUS_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    PLACED_ORDER_ID INT NULL,
    STATUS_CATALOG_ID INT NULL,
    ORDER_STATUS_TIME TIMESTAMP NULL,
    FOREIGN KEY (PLACED_ORDER_ID) REFERENCES PLACED_ORDER (PLACED_ORDER_ID),
    FOREIGN KEY (STATUS_CATALOG_ID) REFERENCES STATUS_CATALOG (STATUS_CATALOG_ID)
);

CREATE TABLE DRIVER (
    DRIVER_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    STATUS_ID INT NULL,
    DRIVER_CODE VARCHAR(50) NULL,
    DRIVER_NAME VARCHAR(100) NULL,
    DRIVER_USERNAME VARCHAR(100) NULL,
    DRIVER_PASSWORD VARCHAR(100) NULL,
    FOREIGN KEY (STATUS_ID) REFERENCES ORDER_STATUS (STATUS_ID)
);

CREATE TABLE PAYMENT_TYPE (
    PAYMENT_TYPE_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    TYPE_NAME VARCHAR(50) NULL
);

CREATE TABLE PAYMENT_DATA (
    PAYMENT_DATA_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    PAYMENT_TYPE_ID INT NULL,
    DATA_NAME VARCHAR(50) NULL,
    DATA_TYPE VARCHAR(50) NULL,
    FOREIGN KEY (PAYMENT_TYPE_ID) REFERENCES PAYMENT_TYPE (PAYMENT_TYPE_ID)
);

CREATE TABLE PAYMENT_DETAILS (
    PAYMENT_DETAILS_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    PLACED_ORDER_ID INT NULL,
    PAYMENT_DATA_ID INT NULL,
    VALUE VARCHAR(50) NULL,
    FOREIGN KEY (PLACED_ORDER_ID) REFERENCES PLACED_ORDER (PLACED_ORDER_ID),
    FOREIGN KEY (PAYMENT_DATA_ID) REFERENCES PAYMENT_DATA (PAYMENT_DATA_ID)
);

CREATE TABLE MENU_CATEGORY (
    MENU_CATEGORY_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CATEGORY_NAME VARCHAR(100) NULL
);

CREATE TABLE MENU_ITEM (
    MENU_ITEM_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ITEM_NAME VARCHAR(100) NULL,
    DESCRIPTION BLOB NULL,
    INGREDIENTS BLOB NULL,
    PRICE DECIMAL(10 , 2 ) NULL,
    MENU_CATEGORY_ID INT NULL,
    FOREIGN KEY (MENU_CATEGORY_ID) REFERENCES MENU_CATEGORY (MENU_CATEGORY_ID)
);

CREATE TABLE IN_ORDER (
    IN_ORDER_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    PLACED_ORDER_ID INT NULL,
    QUANTITIY INT NULL,
    ITEM_PRICE DECIMAL(10 , 2 ) NULL,
    COMMENT VARCHAR(100) NULL,
    MENU_ITEM_ID INT NULL,
    FOREIGN KEY (PLACED_ORDER_ID) REFERENCES PLACED_ORDER (PLACED_ORDER_ID),
    FOREIGN KEY (MENU_ITEM_ID) REFERENCES MENU_ITEM (MENU_ITEM_ID)
);
